name: ImuCamera unit test

on: [push]

jobs:
  build-and-test:
    runs-on: [ubuntu-latest]

    steps:
      # 1. Pull code from the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
        
      # 3. Configure the Cmake project
      - name: Configure CMake
        run: |
          cmake -B build -S .
          cmake --build build -j $(nproc)
          cmake -S . -B build-mock -DBUILD_TESTS=ON -DBUILD_WITH_MOCK_HARDWARE=ON
          cmake --build build-mock -j $(nproc)

      # 4. Execute CTest
      - name: RUN CTest
        run: |
          cd build
          ctest --test-dir build-mock -C Release --output-on-failure


    